### ISSUE TITLE
Definition for rule 'react/jsx-no-duplicate-props' was not found - error on lint

### ISSUE THREAD

**Issue by thebergamo** [Flet/semistandard#38] opened 2015-11-18 14:25 UTC
```sh
  semistandard: Semicolons For All! (https://github.com/Flet/semistandard) 
  /azk/start-hapiness/Azkfile.js:6:1: Definition for rule 'react/jsx-no-duplicate-props' was not found
  /azk/start-hapiness/controllers/todo.js:1:1: Definition for rule 'react/jsx-no-duplicate-props' was not found
  /azk/start-hapiness/index.js:1:1: Definition for rule 'react/jsx-no-duplicate-props' was not found
  /azk/start-hapiness/lib/database.js:1:1: Definition for rule 'react/jsx-no-duplicate-props' was not found
  /azk/start-hapiness/lib/loader.js:1:1: Definition for rule 'react/jsx-no-duplicate-props' was not found
  /azk/start-hapiness/lib/server.js:1:1: Definition for rule 'react/jsx-no-duplicate-props' was not found
  /azk/start-hapiness/models/todo.js:1:1: Definition for rule 'react/jsx-no-duplicate-props' was not found
  /azk/start-hapiness/routes/todo.js:1:1: Definition for rule 'react/jsx-no-duplicate-props' was not found
  /azk/start-hapiness/test/routes/todo.spec.js:1:1: Definition for rule 'react/jsx-no-duplicate-props' was not found
  /azk/start-hapiness/validators/todo.js:1:1: Definition for rule 'react/jsx-no-duplicate-props' was not found
npm ERR! Test failed.  See above for more details.
```

I got this error when I running my linter. Someone can help me to fix this?

**Comment by mipearson** [comment] 2015-11-19 05:55
I'm also seeing this, but only after upgrading to node 4.2 & npm v3.

```
npm --version
3.4.0

node --version
v.4.2.2

npm ls eslint-plugin-react
...
└─┬ semistandard@7.0.2
  └── eslint-plugin-react@2.7.1
```

**Comment by thebergamo** [comment] 2015-11-19 11:35
Hm.. strange.
My current versions. 

```sh
node -v                                                                                                                                                                                                 
v4.1.2
npm --version
3.3.6
```

**Comment by gabmontes** [comment] 2015-11-19 13:27
Same issue. I'm using `linter-js-standard` plugin of Atom.

node@4.2.2
npm@2.14.7
linter-js-standard@3.2.1 + semistandard@7.0.2

The warning is thrown both inside Atom and when running that `semistandard` install from the command line.

Any clue?

**Comment by rankida** [comment] 2016-03-11 15:46
+1 I ran into this issue as well and it is rather annoying that your linter wrongly tells you something is wrong when it isn't - I am not doing React yet get `Definition for rule 'react/jsx-no-duplicate-props' was not found `

**Comment by merktassel** [comment] 2016-03-19 22:25
Is there a solution for this yet? I just switched to Atom and installed linter-js-standard, but `Definition for rule 'react/jsx-no-duplicate-props' was not found` shows up on every file. I typically use Sublime with JSHint, so I'm not sure what to do. I read #37 and tried some basic troubleshooting (reinstalling, ensuring everything's up to date, etcetera), but nothing seems to work.

**Comment by lubien** [comment] 2016-03-20 00:14
@merktassel I don't know if there's a solution. I've just switched to Atom too.
I'm using semistandard with Eslint (linter-eslint) and this config file: [Flet/eslint-config-semistandard](https://github.com/Flet/eslint-config-semistandard)

**Comment by merktassel** [comment] 2016-03-21 18:21
Hmm, I'll have to try that package instead. I've been using [linter-js-standard](https://atom.io/packages/linter-js-standard) with the semistandard style.

**Comment by gabmontes** [comment] 2016-03-21 19:49
@merktassel, a solution is a one-character change as in #72 but considering the solution has been there waiting for more than 4 months, you are right in moving away from this package. It's a shame.

**Comment by merktassel** [comment] 2016-03-22 06:44
Darn. Is this problem strictly related to the linter-js-standard plugin, or the eslint-config-semistandard config as a whole? I'm loving Atom so far, but it's really annoying that semistandard won't work properly.

**Comment by Flet** [comment] 2016-05-16 18:31
Sorry, folks, we've just updated semistandard and its deps. Can someone give the latest a try?

**Comment by lubien** [comment] 2016-05-16 19:45
Not working yet with atom using linter-js-standard. I've been using `eslint-config-semistandard` and it's working fine.
```
node -v
v6.1.0
npm -v
3.8.9
```

**Comment by ricardofbarros** [comment] 2016-05-17 00:43
@lubien I wouldn't jump to conclusions so fast, you're testing this issue with linter-js-standard and should have tested with semistandard instead. And I would recommend to check if you have updated `semistandard` under your projects

**Comment by lubien** [comment] 2016-05-17 01:00
@ricardofbarros I'm not jumping. 
```json
{
  "devDependencies": {
    "babel-eslint": "^6.0.4",
    "semistandard": "^8.0.0"
  },
  "semistandard": {
    "parser": "babel-eslint"
  }
}
```
It's just strange. Using `semistandard` seems ok, but the linter [outputs the error](http://i.imgur.com/MAZsz1L.png).

**Comment by ricardofbarros** [comment] 2016-05-17 01:03
So @Flet release is okay and the problem isn't on `semistandard` but on `linter-js-standard`. I just said that because you could have induced @Flet in error. Mind if I ask you what is the `linter-js-standard` version ?

**Comment by lubien** [comment] 2016-05-17 01:07
I apologize since it sounded like that. Version 3.3.2 of `linter-js-standard`, I've installed today to test it.

**Comment by ricardofbarros** [comment] 2016-05-17 01:13
@Flet I cross-referenced this issue to `linter-js-standard`. As it seems, the problem is on `linter-js-standard` and not on `semistandard`. So I think you can close this.

**Comment by Flet** [comment] 2016-06-01 21:47
Thanks @ricardofbarros

**Closed by Flet** 2016-06-01 21:47 UTC
