### ISSUE TITLE
Cannot use semistandard because of missing dependencies

### ISSUE THREAD

**Issue by gargsms** [Flet/semistandard#229] opened 2017-09-28 12:26 UTC
`semistandard` used to work fine for me, but I recently switched to a new machine with updated `npm`, and whenever I try to use it, I keep getting dependency errors.

This is an example error:
```
semistandard: Unexpected linter output:

Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
```

If I install all the `dependencies` of `semistandard` as `devDependencies` for my project, I simply get new error related to other internal dependencies.

I tried with downgraded `npm`, reinstalled `npm`, and other methods but nothing works.

`npm -v` -> 5.2.0
`node -v` -> v6.11.3

**Comment by gargsms** [comment] 2017-09-28 13:45
I installed `nodejs` and `npm` again. `npm -v` 3.10.10 seems to work.
Leaving this open because npm 5.x.x is still broken.

**Comment by timlesallen** [comment] 2017-10-09 00:33
I'd say this is the same issue as I reported in https://github.com/Flet/semistandard/issues/228

**Comment by lunafi-dorian** [comment] 2017-12-23 21:07
this would be a great improvement.

**Comment by Flet** [comment] 2018-11-06 04:31
Yes this was a duplicate of #228. 

Hey sorry for leaving you hanging on this. I'm going to close this issue because I don't believe this is an problem with modern versions of node/npm. Feel free to reply if this is still a problem!

**Closed by Flet** 2018-11-06 04:31 UTC
